### ISSUE TITLE
traceback.print_exc() being called outside on an except block

### ISSUE THREAD

**Issue by DXsmiley** [MarshalX/atproto#130]
`traceback.print_exc()` only works as expected within an `except` block, otherwise it prints `NoneType: None` which is really difficult to debug. I've been hitting this issue in the wild and don't have a minimal example to actually trigger this line.

https://github.com/MarshalX/atproto/blob/3a68ade797c0c8bd2b120e903ea053bc612f7204/atproto/firehose/client.py#L204

Using `traceback.print_exception(type(exception), exception, exception.__traceback__)` instead gave me some reasonable debugging information.

Running on Python 3.8.10

**Comment by MarshalX** [comment]
Thank you! 

> traceback.print_exc(limit=None, file=None, chain=True)
This is a shorthand for print_exception(sys.exception(), limit, file, chain).

> sys.exception()
This function, when called while an exception handler is executing (such as an except or except* clause), returns the exception **instance** that was caught by this handler. 

Refs:
- https://docs.python.org/3/library/traceback.html#traceback.print_exc
- https://docs.python.org/3/library/sys.html#sys.exception

Ig the right fix will be `traceback.print_exception(expection)` instead of `traceback.print_exc()`
